- hosts: webserver
  gather_facts: False
  tasks:
    - name: install php soap
      yum:
        name: php-soap
        state: latest

    - name: restart httpd
      service: name=httpd state=restarted
